/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ZModal {
    'title': string;
    'visible': boolean;
  }
  interface ZModalAttributes extends StencilHTMLAttributes {
    'onCancel'?: (event: CustomEvent) => void;
    'onOk'?: (event: CustomEvent) => void;
    'title'?: string;
    'visible'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ZModal': Components.ZModal;
  }

  interface StencilIntrinsicElements {
    'z-modal': Components.ZModalAttributes;
  }


  interface HTMLZModalElement extends Components.ZModal, HTMLStencilElement {}
  var HTMLZModalElement: {
    prototype: HTMLZModalElement;
    new (): HTMLZModalElement;
  };

  interface HTMLElementTagNameMap {
    'z-modal': HTMLZModalElement
  }

  interface ElementTagNameMap {
    'z-modal': HTMLZModalElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
